/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FlightEntry {
    totalFlightTime: string;
    instructor: string;
    date: string;
    dateEpoch: bigint;
    exercise: string;
    flightType: Variant_dual_solo;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: Variant_day_night;
    landingCount: bigint;
}
export interface Category {
    name: string;
}
export interface AircraftSummary {
    totalFlightHours: number;
    aircraft: string;
}
export interface UserProfile {
    name: string;
}
export interface StudentTotalHours {
    totalFlightHours: number;
    student: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_day_night {
    day = "day",
    night = "night"
}
export enum Variant_dual_solo {
    dual = "dual",
    solo = "solo"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCategory(categoryType: string, name: string): Promise<void>;
    addFlightEntry(entry: FlightEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCategory(categoryType: string, name: string): Promise<void>;
    deleteFlightEntry(entryId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFlightEntries(filterMonth: string | null, filterStudent: string | null): Promise<Array<FlightEntry>>;
    getFlightEntry(entryId: bigint): Promise<FlightEntry | null>;
    /**
     * / * Computes total flight hours per aircraft by aggregating the caller's flight entries.
     * /    * Groups by aircraft name and sums total flight time per aircraft.
     * /    * Returns an array of aircraft summaries with total hours.
     */
    getTotalFlightHoursByAircraft(): Promise<Array<AircraftSummary>>;
    /**
     * / * Computes total flight hours per student by aggregating the caller's flight entries.
     * /    * Groups by student name and sums total flight time per student.
     * /    * Returns an array of student summaries with total hours.
     */
    getTotalFlightHoursByStudent(): Promise<Array<StudentTotalHours>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCategories(categoryType: string): Promise<Array<Category>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateFlightEntry(entryId: bigint, updatedEntry: FlightEntry): Promise<void>;
}
import type { FlightEntry as _FlightEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1);
            return result;
        }
    }
    async addFlightEntry(arg0: FlightEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlightEntry(to_candid_FlightEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlightEntry(to_candid_FlightEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0, arg1);
            return result;
        }
    }
    async deleteFlightEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFlightEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFlightEntry(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlightEntries(arg0: string | null, arg1: string | null): Promise<Array<FlightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightEntries(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightEntries(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlightEntry(arg0: bigint): Promise<FlightEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightEntry(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightEntry(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalFlightHoursByAircraft(): Promise<Array<AircraftSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalFlightHoursByAircraft();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalFlightHoursByAircraft();
            return result;
        }
    }
    async getTotalFlightHoursByStudent(): Promise<Array<StudentTotalHours>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalFlightHoursByStudent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalFlightHoursByStudent();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCategories(arg0: string): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateFlightEntry(arg0: bigint, arg1: FlightEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFlightEntry(arg0, to_candid_FlightEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFlightEntry(arg0, to_candid_FlightEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_FlightEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightEntry): FlightEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlightEntry]): FlightEntry | null {
    return value.length === 0 ? null : from_candid_FlightEntry_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalFlightTime: string;
    instructor: string;
    date: string;
    dateEpoch: bigint;
    exercise: string;
    flightType: {
        dual: null;
    } | {
        solo: null;
    };
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: {
        day: null;
    } | {
        night: null;
    };
    landingCount: bigint;
}): {
    totalFlightTime: string;
    instructor: string;
    date: string;
    dateEpoch: bigint;
    exercise: string;
    flightType: Variant_dual_solo;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: Variant_day_night;
    landingCount: bigint;
} {
    return {
        totalFlightTime: value.totalFlightTime,
        instructor: value.instructor,
        date: value.date,
        dateEpoch: value.dateEpoch,
        exercise: value.exercise,
        flightType: from_candid_variant_n14(_uploadFile, _downloadFile, value.flightType),
        aircraft: value.aircraft,
        student: value.student,
        takeoffTime: value.takeoffTime,
        landingTime: value.landingTime,
        landingType: from_candid_variant_n15(_uploadFile, _downloadFile, value.landingType),
        landingCount: value.landingCount
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dual: null;
} | {
    solo: null;
}): Variant_dual_solo {
    return "dual" in value ? Variant_dual_solo.dual : "solo" in value ? Variant_dual_solo.solo : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: null;
} | {
    night: null;
}): Variant_day_night {
    return "day" in value ? Variant_day_night.day : "night" in value ? Variant_day_night.night : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlightEntry>): Array<FlightEntry> {
    return value.map((x)=>from_candid_FlightEntry_n12(_uploadFile, _downloadFile, x));
}
function to_candid_FlightEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightEntry): _FlightEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalFlightTime: string;
    instructor: string;
    date: string;
    dateEpoch: bigint;
    exercise: string;
    flightType: Variant_dual_solo;
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: Variant_day_night;
    landingCount: bigint;
}): {
    totalFlightTime: string;
    instructor: string;
    date: string;
    dateEpoch: bigint;
    exercise: string;
    flightType: {
        dual: null;
    } | {
        solo: null;
    };
    aircraft: string;
    student: string;
    takeoffTime: string;
    landingTime: string;
    landingType: {
        day: null;
    } | {
        night: null;
    };
    landingCount: bigint;
} {
    return {
        totalFlightTime: value.totalFlightTime,
        instructor: value.instructor,
        date: value.date,
        dateEpoch: value.dateEpoch,
        exercise: value.exercise,
        flightType: to_candid_variant_n3(_uploadFile, _downloadFile, value.flightType),
        aircraft: value.aircraft,
        student: value.student,
        takeoffTime: value.takeoffTime,
        landingTime: value.landingTime,
        landingType: to_candid_variant_n4(_uploadFile, _downloadFile, value.landingType),
        landingCount: value.landingCount
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_dual_solo): {
    dual: null;
} | {
    solo: null;
} {
    return value == Variant_dual_solo.dual ? {
        dual: null
    } : value == Variant_dual_solo.solo ? {
        solo: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_day_night): {
    day: null;
} | {
    night: null;
} {
    return value == Variant_day_night.day ? {
        day: null
    } : value == Variant_day_night.night ? {
        night: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
