/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FlightEntry = IDL.Record({
  'totalFlightTime' : IDL.Text,
  'instructor' : IDL.Text,
  'date' : IDL.Text,
  'dateEpoch' : IDL.Nat,
  'exercise' : IDL.Text,
  'flightType' : IDL.Variant({ 'dual' : IDL.Null, 'solo' : IDL.Null }),
  'aircraft' : IDL.Text,
  'student' : IDL.Text,
  'takeoffTime' : IDL.Text,
  'landingTime' : IDL.Text,
  'landingType' : IDL.Variant({ 'day' : IDL.Null, 'night' : IDL.Null }),
  'landingCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Category = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addFlightEntry' : IDL.Func([FlightEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFlightEntries' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(FlightEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([IDL.Text], [IDL.Vec(Category)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FlightEntry = IDL.Record({
    'totalFlightTime' : IDL.Text,
    'instructor' : IDL.Text,
    'date' : IDL.Text,
    'dateEpoch' : IDL.Nat,
    'exercise' : IDL.Text,
    'flightType' : IDL.Variant({ 'dual' : IDL.Null, 'solo' : IDL.Null }),
    'aircraft' : IDL.Text,
    'student' : IDL.Text,
    'takeoffTime' : IDL.Text,
    'landingTime' : IDL.Text,
    'landingType' : IDL.Variant({ 'day' : IDL.Null, 'night' : IDL.Null }),
    'landingCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Category = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addFlightEntry' : IDL.Func([FlightEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFlightEntries' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(FlightEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([IDL.Text], [IDL.Vec(Category)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };